# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(default=0)),
                ('overdue_fine', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MediaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='MediaSubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mediaentry',
            name='media_subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.MediaSubTopic'),
        ),
        migrations.AddField(
            model_name='mediaentry',
            name='media_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.MediaTopic'),
        ),
        migrations.AddField(
            model_name='mediaentry',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.MediaType'),
        ),
        migrations.AddField(
            model_name='mediacheckout',
            name='media_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.MediaEntry'),
        ),
        migrations.AddField(
            model_name='mediacheckout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midterm.User'),
        ),
    ]
